### ISSUE TITLE
Program stops with package-related error

### ISSUE THREAD

**Issue by drmandel01** [elisemercury/News-Collector#1]
Thank you for the interesting project and excellent write up both here and in Medium.  I wish I had had some of the newer Python packages that make screen scraping and data analysis so much easier today.  Back to the subject. I am receiving the following error when attempting to run the code, either as a package or as an application. I am unclear as to what my next steps would be to debug it.  Any suggestions?  Thanks. - David

PS D:\Projects\newscollector> type newsletter.py
from newscollector import *

newsletter = NewsCollector()
output = newsletter.create()
PS D:\Projects\newscollector> python .\newsletter.py
INFO: Using custom "sources.json" as source file.
INFO: Using package default "newsletter.html" as template file.
28 articles downloaded from CNN
56 articles downloaded from CNBC
84 total articles downloaded in 0 min 36 sec

Traceback (most recent call last):
  File "D:\Projects\newscollector\newscollector.py", line 120, in find_clusters
    ac = AgglomerativeClustering(distance_threshold=distance_threshhold, n_clusters=None).fit(tfidf_df)
  File "C:\Users\drman\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\cluster\_agglomerative.py", line 955, in fit
    X = self._validate_data(X, ensure_min_samples=2)
  File "C:\Users\drman\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "C:\Users\drman\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\utils\validation.py", line 737, in check_array
    raise TypeError(
TypeError: np.matrix is not supported. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\newscollector\newscollector.py", line 49, in create
    clusters = Processer.find_clusters(news_df, tfidf_df)
  File "D:\Projects\newscollector\newscollector.py", line 137, in find_clusters
    raise Exception(f'Error in "Processer.find_clusters()"')
Exception: Error in "Processer.find_clusters()"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\newscollector\newsletter.py", line 4, in <module>
    output = newsletter.create()
  File "D:\Projects\newscollector\newscollector.py", line 61, in create
    raise Exception(f'Error in "Newsletter.create()"')
Exception: Error in "Newsletter.create()"

**Comment by drmandel01** [comment]
Resolved.  I created a virtual environment, installed the modules based on requirements.txt, and was able to use it with Python3.7 (and probably others).  Nice learning experience for me as I've not programmed with Python in quite some time.
